export const form = [
  {
    retirementAge: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'invalidAge',
          code: 'invalidEmail',
          isRequired: true,
        },
      ],
      name: 'retirementAge',
      placeholder: 'Age of retirement ',
      type: 'number',
      label: 'When you would like to retire?',
      id: 'field-99a38c7d-c230-464b-8bf0-9dcaf49c6e10',
      _isTouched: false,
    },
    currentAge: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'invalidLastName',
          code: 'invalidEmail',
          isRequired: true,
        },
      ],
      name: 'currentAge',
      placeholder: 'Current Age',
      type: 'number',
      label: 'How old are you?',
      id: 'field-3e28ee4b-206f-46e6-b3e6-c93ba366cbf3',
      _isTouched: false,
    },
    spouseAge: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'invalidScreenName',
          code: 'invalidEmail',
          isRequired: true,
        },
      ],
      name: 'spouseAge',
      placeholder: 'Spouse Age',
      type: 'number',
      label: 'How old is your spouse?',
      id: 'field-b73027ad-1722-47a4-bc53-a3bcffee245b',
      _isTouched: false,
    },
    annualIncome: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'invalidEmail',
          code: 'invalidEmail',
          isRequired: true,
        },
      ],
      name: 'annualIncome',
      placeholder: 'Your gross income',
      type: 'number',
      label: 'Annual Income',
      id: 'field-9a92b986-e8c7-408b-b85a-0cee5e4d06fb',
      _isTouched: false,
    },
    partnerIncome: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'partnerIncome',
      placeholder: 'Your partner’s gross income',
      type: 'number',
      label: ' ',
      id: 'field-a1d657ba-1d9f-4451-b75f-dd6478acb5cf',
      _isTouched: false,
    },
    riskTolerance: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'riskTolerance',
      placeholder: '',
      type: 'slider',
      label: 'What’s your risk tolerance?  ',
      id: 'field-dad3f8cf-50d0-44ea-98ce-41a18fd796c1',
      _isTouched: false,
    },
    numberofDependents: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'numberofDependents',
      placeholder: 'How many kids do you have?',
      type: 'string',
      label: ' ',
      id: 'field-60fa95bf-1c8e-4a7a-af50-db88e5d48dfb',
      _isTouched: false,
    },
    investimentsAndSavings: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'investimentsAndSavings',
      placeholder: 'Do you have investments & savings?',
      type: 'dropdown',
      label: 'Investments & Savings',
      id: 'field-f22072c0-9403-40e6-8384-46bc91fb9014',
      _isTouched: false,
    },
    investimentsType: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'investimentsType',
      placeholder: 'What types of Investments & Savings accounts do you have?',
      type: 'multiSelect',
      label: 'if your answer is yes',
      id: 'field-bf63bd15-2212-4530-a25c-be4adde12e50',
      _isTouched: false,
    },
    investimentsAmount: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'investimentsAmount',
      placeholder: ' ',
      type: 'string',
      label: '(for each account type selected, $ amount box appears)',
      id: 'field-2a29417e-2235-49c8-b6e6-a6c3dea6649c',
      _isTouched: false,
    },
    benefitWorkplacePension: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'benefitWorkplacePension',
      placeholder: 'Do you have a work place pension?',
      type: 'string',
      label: 'Defined benefit workplace pension',
      id: 'field-b81624b3-3caa-43a3-a715-a89a33410c56',
      _isTouched: false,
    },
    yesBenefit: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'yesBenefit',
      placeholder: 'How much will it pay in retirement per year?',
      type: 'number',
      label: 'If answer is “yes”',
      id: 'field-1ec32826-4355-45b3-b642-39b21608a733',
      _isTouched: false,
    },
    monthlySavings: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'monthlySavings',
      placeholder: 'Monthly savings',
      type: 'number',
      label: ' ',
      id: 'field-842ee75a-6c59-4e2d-b4c1-8424c8e4d2b4',
      _isTouched: false,
    },
    rentHome: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'rentHome',
      placeholder: 'Do you rent or own?',
      type: 'dropdown',
      label: 'Your Home',
      id: 'rentHome',
      _isTouched: false,
    },
    homeWorth: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'homeWorth',
      placeholder: 'How much is your home worth?',
      type: 'number',
      label: 'If answer is “own”',
      id: 'field-0d3b9d69-ead4-484e-b838-3e6243289310',
      _isTouched: false,
    },
    mortgageBalance: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'mortgageBalance',
      placeholder: 'What’s the remaining mortgage balance?',
      type: 'number',
      label: ' ',
      id: 'field-4b5f5373-4131-4655-a812-9ac1a13ecc8e',
      _isTouched: false,
    },
    mortgagePayment: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'mortgagePayment',
      placeholder: 'Your mortgage payment (a month)',
      type: 'number',
      label: ' ',
      id: 'field-baf5907f-232e-4591-a854-1f91101c7753',
      _isTouched: false,
    },
    rentPerMonth: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'rentPerMonth',
      placeholder: 'Your rent per month',
      type: 'number',
      label: 'If answer is “rent”',
      id: 'field-4257d90e-ba73-4f02-a5f7-a72f39f4ecde',
      _isTouched: false,
    },
    debt: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'debt',
      placeholder: 'Do you have any debt?',
      type: 'dropdown',
      label: 'Your Debt',
      id: 'field-34d32413-4198-4704-b548-0b8fceca3c6c',
      _isTouched: false,
    },
    yesDebt: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'yesDebt',
      placeholder: 'Which of these are you currently paying off?',
      type: 'multiSelect',
      label: 'If answer is “Yes”',
      id: 'field-ba15694e-c50e-4ad0-ab94-7e013d8e95b3',
      _isTouched: false,
    },
    yesCreditCard: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'yesCreditCard',
      placeholder: 'Do you pay off your entire balance every month?',
      type: 'dropdown',
      label: 'If answer is “Credit Card”',
      id: 'field-641efd80-007a-48fe-a998-b8ed3be9e9e9',
      _isTouched: false,
    },
    noCreditCard: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'noCreditCard',
      placeholder: 'Balance owing, Avg. monthly payment',
      type: 'number',
      label: 'If answer is “No”',
      id: 'field-b7c83dfe-e98e-4a3f-909a-0e22eec223e8',
      _isTouched: false,
    },
    otherAnswers: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'otherAnswers',
      placeholder: 'Balance owing, Avg. monthly payment',
      type: 'number',
      label: 'For all other answer types',
      id: 'field-20914e03-678e-4433-bd5d-ff4dab763791',
      _isTouched: false,
    },
    lifeExpectancy: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'lifeExpectancy',
      placeholder: 'Your Gender, Are you a smoker?',
      type: 'dropdown',
      label: 'Life Expectancy',
      id: 'field-248f365f-9e98-43fe-bfbe-2aad1b7ea1ca',
      _isTouched: false,
    },
    zipCode: {
      _value: '',
      _errors: [],
      _validators: [
        {
          message: 'required',
          code: 'required',
          isRequired: true,
        },
        {
          message: 'passwordInvalidLength',
          code: 'minLength',
          isRequired: true,
          minLength: 6,
        },
      ],
      name: 'zipCode',
      placeholder: 'What zip code do you use to file your taxes?',
      type: 'number',
      label: 'Zip Code',
      id: 'field-04540b37-151e-421a-a749-ba3a596f65d0',
      _isTouched: false,
    },
  },
];
